// Code generated by goctl. DO NOT EDIT.
package types

type Resp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg,omitempty"`
	Data interface{} `json:"data,omitempty"`
}

type SelectGameUserReq struct {
	GameUserId int64 `json:"gameUserId,string"`
}

type SelectGameUsersReq struct {
	GameUserIds []int64 `json:"gameUserIds,string"`
}

type LoginReq struct {
	Usr string `json:"usr"`
	Pwd string `json:"pwd"`
}

type LoginGameReq struct {
	Channel uint8  `json:"channel"`
	Usr     string `json:"usr"`
	Pwd     string `json:"pwd"`
}

type SendOtpReq struct {
	Channel uint8  `json:"channel"`
	Phone   string `json:"phone"`
}

type OtpLoginGameReq struct {
	Phone string `json:"phone"`
	Otp   string `json:"otp"`
}

type BuyShopItemReq struct {
	SelectGameUsersReq
	Selected []map[string]interface{} `json:"selected"`
}
